# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.7

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\vinicius\floobits\share\kaueel\trabalho-angelis

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\vinicius\floobits\share\kaueel\trabalho-angelis

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files (x86)\JetBrains\CLion 2017.1\bin\cmake\bin\cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\vinicius\floobits\share\kaueel\trabalho-angelis\CMakeFiles C:\Users\vinicius\floobits\share\kaueel\trabalho-angelis\CMakeFiles\progress.marks
	$(MAKE) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\vinicius\floobits\share\kaueel\trabalho-angelis\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FT_Bakery

# Build rule for target.
FT_Bakery: cmake_check_build_system
	$(MAKE) -f CMakeFiles\Makefile2 FT_Bakery
.PHONY : FT_Bakery

# fast build rule for target.
FT_Bakery/fast:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/build
.PHONY : FT_Bakery/fast

FT_bakery.obj: FT_bakery.cpp.obj

.PHONY : FT_bakery.obj

# target to build an object file
FT_bakery.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/FT_bakery.cpp.obj
.PHONY : FT_bakery.cpp.obj

FT_bakery.i: FT_bakery.cpp.i

.PHONY : FT_bakery.i

# target to preprocess a source file
FT_bakery.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/FT_bakery.cpp.i
.PHONY : FT_bakery.cpp.i

FT_bakery.s: FT_bakery.cpp.s

.PHONY : FT_bakery.s

# target to generate assembly for a file
FT_bakery.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/FT_bakery.cpp.s
.PHONY : FT_bakery.cpp.s

a02ex00.obj: a02ex00.cpp.obj

.PHONY : a02ex00.obj

# target to build an object file
a02ex00.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex00.cpp.obj
.PHONY : a02ex00.cpp.obj

a02ex00.i: a02ex00.cpp.i

.PHONY : a02ex00.i

# target to preprocess a source file
a02ex00.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex00.cpp.i
.PHONY : a02ex00.cpp.i

a02ex00.s: a02ex00.cpp.s

.PHONY : a02ex00.s

# target to generate assembly for a file
a02ex00.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex00.cpp.s
.PHONY : a02ex00.cpp.s

a02ex01_a.obj: a02ex01_a.cpp.obj

.PHONY : a02ex01_a.obj

# target to build an object file
a02ex01_a.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex01_a.cpp.obj
.PHONY : a02ex01_a.cpp.obj

a02ex01_a.i: a02ex01_a.cpp.i

.PHONY : a02ex01_a.i

# target to preprocess a source file
a02ex01_a.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex01_a.cpp.i
.PHONY : a02ex01_a.cpp.i

a02ex01_a.s: a02ex01_a.cpp.s

.PHONY : a02ex01_a.s

# target to generate assembly for a file
a02ex01_a.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex01_a.cpp.s
.PHONY : a02ex01_a.cpp.s

a02ex03.obj: a02ex03.cpp.obj

.PHONY : a02ex03.obj

# target to build an object file
a02ex03.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03.cpp.obj
.PHONY : a02ex03.cpp.obj

a02ex03.i: a02ex03.cpp.i

.PHONY : a02ex03.i

# target to preprocess a source file
a02ex03.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03.cpp.i
.PHONY : a02ex03.cpp.i

a02ex03.s: a02ex03.cpp.s

.PHONY : a02ex03.s

# target to generate assembly for a file
a02ex03.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03.cpp.s
.PHONY : a02ex03.cpp.s

a02ex03_a.obj: a02ex03_a.cpp.obj

.PHONY : a02ex03_a.obj

# target to build an object file
a02ex03_a.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_a.cpp.obj
.PHONY : a02ex03_a.cpp.obj

a02ex03_a.i: a02ex03_a.cpp.i

.PHONY : a02ex03_a.i

# target to preprocess a source file
a02ex03_a.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_a.cpp.i
.PHONY : a02ex03_a.cpp.i

a02ex03_a.s: a02ex03_a.cpp.s

.PHONY : a02ex03_a.s

# target to generate assembly for a file
a02ex03_a.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_a.cpp.s
.PHONY : a02ex03_a.cpp.s

a02ex03_b.obj: a02ex03_b.cpp.obj

.PHONY : a02ex03_b.obj

# target to build an object file
a02ex03_b.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_b.cpp.obj
.PHONY : a02ex03_b.cpp.obj

a02ex03_b.i: a02ex03_b.cpp.i

.PHONY : a02ex03_b.i

# target to preprocess a source file
a02ex03_b.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_b.cpp.i
.PHONY : a02ex03_b.cpp.i

a02ex03_b.s: a02ex03_b.cpp.s

.PHONY : a02ex03_b.s

# target to generate assembly for a file
a02ex03_b.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_b.cpp.s
.PHONY : a02ex03_b.cpp.s

a02ex03_c.obj: a02ex03_c.cpp.obj

.PHONY : a02ex03_c.obj

# target to build an object file
a02ex03_c.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_c.cpp.obj
.PHONY : a02ex03_c.cpp.obj

a02ex03_c.i: a02ex03_c.cpp.i

.PHONY : a02ex03_c.i

# target to preprocess a source file
a02ex03_c.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_c.cpp.i
.PHONY : a02ex03_c.cpp.i

a02ex03_c.s: a02ex03_c.cpp.s

.PHONY : a02ex03_c.s

# target to generate assembly for a file
a02ex03_c.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_c.cpp.s
.PHONY : a02ex03_c.cpp.s

a02ex03_d.obj: a02ex03_d.cpp.obj

.PHONY : a02ex03_d.obj

# target to build an object file
a02ex03_d.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_d.cpp.obj
.PHONY : a02ex03_d.cpp.obj

a02ex03_d.i: a02ex03_d.cpp.i

.PHONY : a02ex03_d.i

# target to preprocess a source file
a02ex03_d.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_d.cpp.i
.PHONY : a02ex03_d.cpp.i

a02ex03_d.s: a02ex03_d.cpp.s

.PHONY : a02ex03_d.s

# target to generate assembly for a file
a02ex03_d.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_d.cpp.s
.PHONY : a02ex03_d.cpp.s

a02ex03_e.obj: a02ex03_e.cpp.obj

.PHONY : a02ex03_e.obj

# target to build an object file
a02ex03_e.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_e.cpp.obj
.PHONY : a02ex03_e.cpp.obj

a02ex03_e.i: a02ex03_e.cpp.i

.PHONY : a02ex03_e.i

# target to preprocess a source file
a02ex03_e.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_e.cpp.i
.PHONY : a02ex03_e.cpp.i

a02ex03_e.s: a02ex03_e.cpp.s

.PHONY : a02ex03_e.s

# target to generate assembly for a file
a02ex03_e.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_e.cpp.s
.PHONY : a02ex03_e.cpp.s

a02ex03_f.obj: a02ex03_f.cpp.obj

.PHONY : a02ex03_f.obj

# target to build an object file
a02ex03_f.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_f.cpp.obj
.PHONY : a02ex03_f.cpp.obj

a02ex03_f.i: a02ex03_f.cpp.i

.PHONY : a02ex03_f.i

# target to preprocess a source file
a02ex03_f.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_f.cpp.i
.PHONY : a02ex03_f.cpp.i

a02ex03_f.s: a02ex03_f.cpp.s

.PHONY : a02ex03_f.s

# target to generate assembly for a file
a02ex03_f.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_f.cpp.s
.PHONY : a02ex03_f.cpp.s

a02ex03_g.obj: a02ex03_g.cpp.obj

.PHONY : a02ex03_g.obj

# target to build an object file
a02ex03_g.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_g.cpp.obj
.PHONY : a02ex03_g.cpp.obj

a02ex03_g.i: a02ex03_g.cpp.i

.PHONY : a02ex03_g.i

# target to preprocess a source file
a02ex03_g.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_g.cpp.i
.PHONY : a02ex03_g.cpp.i

a02ex03_g.s: a02ex03_g.cpp.s

.PHONY : a02ex03_g.s

# target to generate assembly for a file
a02ex03_g.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_g.cpp.s
.PHONY : a02ex03_g.cpp.s

a02ex03_h.obj: a02ex03_h.cpp.obj

.PHONY : a02ex03_h.obj

# target to build an object file
a02ex03_h.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_h.cpp.obj
.PHONY : a02ex03_h.cpp.obj

a02ex03_h.i: a02ex03_h.cpp.i

.PHONY : a02ex03_h.i

# target to preprocess a source file
a02ex03_h.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_h.cpp.i
.PHONY : a02ex03_h.cpp.i

a02ex03_h.s: a02ex03_h.cpp.s

.PHONY : a02ex03_h.s

# target to generate assembly for a file
a02ex03_h.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_h.cpp.s
.PHONY : a02ex03_h.cpp.s

a02ex03_i.obj: a02ex03_i.cpp.obj

.PHONY : a02ex03_i.obj

# target to build an object file
a02ex03_i.cpp.obj:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_i.cpp.obj
.PHONY : a02ex03_i.cpp.obj

a02ex03_i.i: a02ex03_i.cpp.i

.PHONY : a02ex03_i.i

# target to preprocess a source file
a02ex03_i.cpp.i:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_i.cpp.i
.PHONY : a02ex03_i.cpp.i

a02ex03_i.s: a02ex03_i.cpp.s

.PHONY : a02ex03_i.s

# target to generate assembly for a file
a02ex03_i.cpp.s:
	$(MAKE) -f CMakeFiles\FT_Bakery.dir\build.make CMakeFiles/FT_Bakery.dir/a02ex03_i.cpp.s
.PHONY : a02ex03_i.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... FT_Bakery
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... FT_bakery.obj
	@echo ... FT_bakery.i
	@echo ... FT_bakery.s
	@echo ... a02ex00.obj
	@echo ... a02ex00.i
	@echo ... a02ex00.s
	@echo ... a02ex01_a.obj
	@echo ... a02ex01_a.i
	@echo ... a02ex01_a.s
	@echo ... a02ex03.obj
	@echo ... a02ex03.i
	@echo ... a02ex03.s
	@echo ... a02ex03_a.obj
	@echo ... a02ex03_a.i
	@echo ... a02ex03_a.s
	@echo ... a02ex03_b.obj
	@echo ... a02ex03_b.i
	@echo ... a02ex03_b.s
	@echo ... a02ex03_c.obj
	@echo ... a02ex03_c.i
	@echo ... a02ex03_c.s
	@echo ... a02ex03_d.obj
	@echo ... a02ex03_d.i
	@echo ... a02ex03_d.s
	@echo ... a02ex03_e.obj
	@echo ... a02ex03_e.i
	@echo ... a02ex03_e.s
	@echo ... a02ex03_f.obj
	@echo ... a02ex03_f.i
	@echo ... a02ex03_f.s
	@echo ... a02ex03_g.obj
	@echo ... a02ex03_g.i
	@echo ... a02ex03_g.s
	@echo ... a02ex03_h.obj
	@echo ... a02ex03_h.i
	@echo ... a02ex03_h.s
	@echo ... a02ex03_i.obj
	@echo ... a02ex03_i.i
	@echo ... a02ex03_i.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

